### ISSUE TITLE
Semantic release not publishing to npm if commit is `chore` or `docs`

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/create-extension#27]

**Comment by ryan-blunden** [comment]
This is by design but can be customized - https://github.com/semantic-release/commit-analyzer#release-rules

**Comment by felixfbecker** [comment]
Why would this be desired?

**Comment by ryan-blunden** [comment]
So README.md changes would trigger a new release.

**Comment by ryan-blunden** [comment]
If the `README.md` for example needs "fixing", then it should be a `fix:` commit and not a `docs:` commit. 

This relies on the developer knowing how semantic-release works but if they're contributing to this project, they need to know that anyway. 

Going to close.
